module.exports = {
    "about": "About",
    "contact": "Contact",
    "home": "Home",
    "services": "Services",
    "address_text": "220002 Minsk, ul. Kiseleva, 55, office 22",
    "email": "Email",
    "name": "Name",
    "submit": "Submit",
    "copyright": "© 2016 Aenean porta condimentum, ALL RIGHTS RESERVED.",
    "message": "Message",

    "experience": "experience",
    "blah_blah_blah": "blah blah blah",
    "why_choose_us": "WHY CHOOSE US",
    "legal_and_advisory_services": "Legal and advisory (consulting) services, legal support of business",
    "our_company_specializes_in_legal_consulting_business": "Our company specializes in legal consulting business. System Legal support our",
    "the_accumulated_experience_allows_us" : "The accumulated experience allows us to professionally and effectively organize and maintain your business. support existing business, in which lawyers have a different range of services, allowing to work without fear.",
    "our_customers": "our customers",
    "80_percent_of_our_customers_are_companies_from_the_it_sphere": "80% of our customers are companies from the IT sphere",
    "work_experience_in_the_field_of_law_for_over_10_years": "work experience in the field of law for over 10 years",
    "certified_lawyer_licensed": "Certified lawyer licensed to provide legal services to the Ministry of Justice of the Republic of Belarus",
    "experience_in_state_control_and_supervisory_bodies": "Experience in state control and supervisory bodies, senior positions in companies specializing in the provision of legal services",
    "conducting_cases_in_court": "Conducting cases in court",
    "working_with_bailiffs_experience": "Working with bailiffs experience",
    "communication_with_contractors_and_correspondence_in_english": "Communication with contractors and correspondence in English",
    "confidentiality": "Confidentiality",

    "services_provided_include": "Services provided include",
    "registration_and_reorganization_of_legal_entities": "Registration and reorganization of legal entities",
    "detailed_study_of_constituent_documents": "Detailed study of constituent documents",
    "bringing_the_constituent_documents_in_compliance_with_the_law": "Bringing the constituent documents in compliance with the law",
    "registration_and_reorganization_of_legal_entities_branches_and_representative_offices": "Registration and reorganization of legal entities branches and representative offices",
    "registration_of_branches_and_representative_offices": "Registration of branches and representative offices",
    "amendments_and_preparation_of_the_new_edition_of_the_charter": "Amendments and preparation of the new edition of the Charter",
    "support_for_the_purchase_and_sale_transactions_of_shares_in_the_authorized_capital": "Support for the purchase and sale transactions of shares in the authorized capital",
    "change_of_name_of_a_legal_entity": "Change of name of a legal entity",
    "document_preparation": "Document preparation, support of registration as an individual entrepreneur",
    "support_economic_activity": "Support economic activity",
    "work_with_personnel": "Work with personnel",
    "advice_on_legal_aspects_of_doing_business": "Advice on legal aspects of doing business",
    "drafting_and_legal_examination_of_economic_contracts": "Drafting and legal examination of economic contracts",
    "obtaining_a_special_permit_for_labor_activity_in_the_republic_of_belarus_for_foreign_citizens": "Obtaining a special permit for labor activity in the Republic of Belarus for foreign citizens",
    "obtaining_licenses_and_special_permits": "Obtaining licenses and special permits",
    "obtaining_patents": "Obtaining patents",
    "copyright_protection": "Copyright protection",
    "with_claims_related_work": "With claims related work",
    "negotiation_and_settlement_of_disputes_out_of_court": "Negotiation and settlement of disputes out of court",
    "preparation_of_claim_letters": "Preparation of claim letters",
    "preparation_of_applications_to_commit_the_executive_inscriptions": "Preparation of applications to commit the executive inscriptions",
    "support_of_debt_collection": "Support of debt collection",
    "work_in_the_field_of_administrative_law": "Work in the field of administrative law",
    "support_and_legal_protection_in_cases_of_administrative_offenses": "Support and legal protection in cases of administrative offenses",
    "counseling": "Counseling",
    "consultancy_in_the_field_of_law": "Consultancy in the field of law",
    "preparation_of_official_requests": "Preparation of official requests"
};