module.exports = {
    "about_us": "About us",
    "contact": "Contacts",
    "home": "Home",
    "rates": "Rates",
    "services": "Services",
    "address_text": "Rakovskaya Street 19A, Minsk",
    "email": "Email",
    "name": "Name",
    "submit": "Submit",
    "copyright": "© 2016, ALL RIGHTS RESERVED.",
    "message": "Message",
    "gravis": "Gravis",
    "consulting_company": "Consulting company",

    "show_content": "show content",
    "hide_content": "hide content",

    "blah_blah_blah": "blah blah blah",
    "why_choose_us": "WHY CHOOSE US",
    "legal_and_advisory_services": "Legal counseling and legal support of business",
    "our_company_specializes_in_legal_consulting_business": "We provide legal support to the system of economic activity. We help create business ideas find their realization",
    "the_accumulated_experience_allows_us" : "The accumulated experience allows us to professionally and effectively organize and maintain your business. support existing business, in which lawyers have a different range of services, allowing to work without fear.",
    "our_customers": "our customers",

    "areas_of_our_professional_interest": "Areas of our professional interest",
    "information_technology": "Information Technology",
    "retail_and_services": "Retail and Services",
    "wholesale_and_b2b": "Wholesale and B2B",
    "foreign_economic_activity": "Foreign economic activity",
    "investment_and_production": "Investment and Production",

    "types_of_services": "Types of services",
    "full_legal_support_of_business": "Full legal support for business",
    "registration_and_reorganization_of_enterprises": "Registration and reorganization of enterprises",
    "debt_collection": "Debt collection",
    "representation_of_clients_in_state_bodies": "Working with government agencies",
    "work_with_foreign_companies_and_migrant_workers": "Work with foreign companies and migrant workers",
    "investment_documentation_development": "Investment documentation development",

    "by_choosing_us,_you_get": "By choosing us, you get",
    "comprehensive_legal_services_by_a_team_of_professionals": "Comprehensive legal services by a team of professionals",
    "flexible_terms_of_cooperation,_based_on_your_priorities": "Flexible terms of cooperation, based on your priorities",
    "legal_protection_for_your_business": "Legal protection for your business",

    "work_experience_in_the_field_of_law_for_over_10_years": "work experience in the field of law for over 10 years",
    "certified_lawyer_licensed": "Certified lawyer licensed to provide legal services to the Ministry of Justice of the Republic of Belarus",
    "experience_in_state_control_and_supervisory_bodies": "Experience in state control and supervisory bodies, senior positions in companies specializing in the provision of legal services",
    "conducting_cases_in_court": "Conducting cases in court",
    "working_with_bailiffs_experience": "Working with bailiffs experience",
    "communication_with_contractors_and_correspondence_in_english": "Communication with contractors and correspondence in English",
    "confidentiality": "Confidentiality",

    //RATES
    "byn_for_residents_of_the_republic_of_belarus_and_euro__for_non-residents_of_the_republic_of_belarus": "BYN for residents of the Republic of Belarus and EURO  for non-residents of the Republic of Belarus",

    "rates_for_legal_services_in_the_field_of_state_registration_(reorganization)_of_business_entities_llc_(odl),_pue,_sp": "Rates for legal services in the field of state registration (reorganization) of business entities LLC (ODL), PUE, SP",
    "preparation_of_documents_for_the_state_registration_of_the_company_(alc),_pue": "Preparation of documents for the state registration of the Company (ALC), PUE",
    "full_legal_support_of_state_registration_ltd_(odl),_pue": "Full legal support of state registration Ltd. (ODL), PUE",
    "full_legal_support_of_the_state_registration_of_ip": "Full legal support of the state registration of IP",
    "full_legal_support_of_the_procedure_of_legal_entity_reorganization": "Full legal support of the procedure of legal entity reorganization",

    "rates_for_legal_services_in_the_field_of_representation": "Rates for legal services in the field of representation",
    "full_legal_support_of_opening_the_representation_of_non-resident_organization": "Full legal support of opening the representation of non-resident organization of the Republic of Belarus in the Republic of Belarus",

    "rates_for_legal_services_when_making_changes_to_the_charter_of_the_business_entity": "Rates for legal services when making changes to the charter of the business entity",
    "preparation_of_documents_for_making_changes_to_the_constituent_documents_of_a_legal_entity_in_connection_with_the_change_of_its_name": "Preparation of documents for making changes to the constituent documents of a legal entity in connection with the change of its name, the size of the statutory fund, the membership, the legislation, according to which the required changes and (or) additions to other factual circumstances contained in the statutes",

    "rates_for_other_legal_services_in_the_field_of_corporate_law": "Rates for other legal services in the field of corporate law",
    "preparation_of_draft_documents_for_convening_and_holding_the_general_meeting_of_the_business_association": "Preparation of draft documents for convening and holding the general meeting of the business association",
    "preparation_of_draft_documents_for_the_transaction_for_the_disposal_of_shares_in_the_authorized_capital_of_llc_(odl)": "Preparation of draft documents for the transaction for the disposal of shares in the authorized capital of LLC (ODL)",

    "rates_for_the_development_of_projects_of_different_types_of_contracts": "Rates for the development of projects of different types of contracts",
    "economic_development_of_the_draft_treaty": "Economic Development of the draft treaty",
    "drafting_foreign_economic_agreement": "Drafting foreign economic agreement",
    "development_of_the_labor_contract_projects,_contracts,_contract": "Development of the labor contract projects, contracts, contract",

    "rates_for_legal_services_for_legal_entities_in_the_sphere_of_labor_migration": "Rates for legal services for legal entities in the sphere of labor migration",
    "preparation,_collection_of_documents,_support_for_obtaining_the_right_of_residence_in_the_republic_of_belarus": "Preparation, collection of documents, support for obtaining the right of residence in the Republic of Belarus",
    "preparation,_collection_of_documents,_support_for_obtaining_a_residence_permit_in_the_republic_of_belarus": "Preparation, collection of documents, support for obtaining a residence permit in the Republic of Belarus",
    "preparation_of_documents_for_obtaining_a_special_right_to_engage_in_work_in_the_republic_of_belarus": "Preparation of documents for obtaining a special right to engage in work in the Republic of Belarus",
    "full_legal_support_for_obtaining_a_special_right_to_engage_in_work_in_the_republic_of_belarus": "Legal support for obtaining a special right to engage in work in the Republic of Belarus",

    "rates_for_the_preparation_of_legal_documents_for_courts,_enforcement_authorities,_notaries": "Rates for the preparation of legal documents for courts, enforcement authorities, notaries",
    "study_materials_and_giving_advice_on_possible_options_for_the_protection_of_rights_and_legal_interests_of_the_client": "Study materials and giving advice on possible options for the protection of rights and legal interests of the client",
    "consultation_on_the_possibility_of_filing_a_claim_to_the_economic_court,_the_formation_of_a_position_on_the_case": "Consultation on the possibility of filing a claim to the Economic Court, the formation of a position on the case",
    "preparation_of_claims_(proposal_for_voluntary_settlement_of_the_dispute),_the_response_to_the_claim": "Preparation of claims (proposal for voluntary settlement of the dispute), the response to the claim",
    "preparing_the_statement_of_claim,_recall_the_statement_of_claim": "Preparing the statement of claim, recall the statement of claim",
    "preparation_of_the_application_for_commencement_of_writ_proceedings,_comment_on_the_statement_of_writ_proceedings": "Preparation of the application for commencement of writ proceedings, comment on the statement of writ proceedings",
    "preparation_of_appeal,_cassation_complaints,_complaints_of_supervision,_revocation_on_appeal,_appeal,_on_newly_discovered_facts": "Preparation of appeal, cassation complaints, complaints of supervision, revocation on appeal, appeal, on newly discovered facts",
    "preparation_of_the_extradition_documents_of_executive_inscriptions": "Preparation of the extradition documents of executive inscriptions",
    "preparing_the_application_for_commencement_of_enforcement_proceedings": "Preparing the application for commencement of enforcement proceedings",
    "preparation_of_other_procedural_documents": "Preparation of other procedural documents",
    "representation_in_enforcement_proceedings": "Representation in enforcement proceedings",

    "rates_for_legal_advice_and_legal_assistance_for_any_other_legal_matters": "Rates for legal advice and legal assistance for any other legal matters",
    "verbal_legal_advice": "Verbal legal advice",
    "written_legal_advice": "Written legal advice",
    "representing_clients_before_government_agencies,_contractors_and_other_third_parties_in_the_course_of_his_instructions": "Representing clients before government agencies, contractors and other third parties in the course of his instructions",
    "selection_of_materials,_legislation_on_specific_customer_category": "Selection of materials, legislation on specific customer category",

    "or_%_of_foreclosure": "or % of foreclosure",
    "per_hour": "per hour",
    //Rates END

    "our_services_-_a_guarantee_of_the_right_steps_in_the_business": "Our services - a guarantee of the right steps in the business",

    "services_provided_include": "Services provided include",
    "registration_and_reorganization_of_legal_entities": "Registration and reorganization of legal entities",
    "detailed_study_of_constituent_documents": "Detailed study of constituent documents",
    "bringing_the_constituent_documents_in_compliance_with_the_law": "Bringing the constituent documents in compliance with the law",
    "registration_and_reorganization_of_legal_entities_branches_and_representative_offices": "Registration and reorganization of legal entities branches and representative offices",
    "registration_of_branches_and_representative_offices": "Registration of branches and representative offices",
    "amendments_and_preparation_of_the_new_edition_of_the_charter": "Amendments and preparation of the new edition of the Charter",
    "support_for_the_purchase_and_sale_transactions_of_shares_in_the_authorized_capital": "Support for the purchase and sale transactions of shares in the authorized capital",
    "change_of_name_of_a_legal_entity": "Change of name of a legal entity",
    "document_preparation": "Document preparation, support of registration as an individual entrepreneur",
    "support_economic_activity": "Support economic activity",
    "work_with_personnel": "Work with personnel",
    "advice_on_legal_aspects_of_doing_business": "Advice on legal aspects of doing business",
    "drafting_and_legal_examination_of_economic_contracts": "Drafting and legal examination of economic contracts",
    "obtaining_a_special_permit_for_labor_activity_in_the_republic_of_belarus_for_foreign_citizens": "Obtaining a special permit for labor activity in the Republic of Belarus for foreign citizens",
    "obtaining_licenses_and_special_permits": "Obtaining licenses and special permits",
    "obtaining_patents": "Obtaining patents",
    "copyright_protection": "Copyright protection",
    "with_claims_related_work": "With claims related work",
    "negotiation_and_settlement_of_disputes_out_of_court": "Negotiation and settlement of disputes out of court",
    "preparation_of_claim_letters": "Preparation of claim letters",
    "preparation_of_applications_to_commit_the_executive_inscriptions": "Preparation of applications to commit the executive inscriptions",
    "support_of_debt_collection": "Support of debt collection",
    "work_in_the_field_of_administrative_law": "Work in the field of administrative law",
    "support_and_legal_protection_in_cases_of_administrative_offenses": "Support and legal protection in cases of administrative offenses",
    "counseling": "Counseling",
    "consultancy_in_the_field_of_law": "Consultancy in the field of law",
    "preparation_of_official_requests": "Preparation of official requests"
};