module.exports = {
    "about": "О нас",
    "contact": "Контакты",
    "home": "Главная",
    "rates": "Тарифы",
    "services": "Услуги",
    "address_text": "улица Раковская 19А, Минск",
    "email": "Почта",
    "name": "Имя",
    "submit": "Отправить",
    "copyright": "© 2016, ВСЕ ПРАВА ЗАЩИЩЕНЫ.",
    "message": "Сообщение",

    "show_content": "показать содержимое",
    "hide_content": "скрыть содержимое",

    "blah_blah_blah": "бла бла бла",
    "why_choose_us": "Почему стоит выбрать нас",
    "legal_and_advisory_services": "Юридический консалтинг и правовое сопровождение бизнеса",
    "our_company_specializes_in_legal_consulting_business": "Наша компания специализируется на юридическом консалтинге бизнеса. Системная правовая поддержка наш",
    "the_accumulated_experience_allows_us" : "Наработанный опыт позволяет нам профессионально и эффективно организовать и обслуживать Ваш бизнес. поддержка действующего бизнеса, в рамках которой юристы оказывают различный спектр услуг, позволяющих работать без опасений.",
    "our_customers": "Наши клиенты",

    "work_experience_in_the_field_of_law_for_over_10_years": "Стаж работы в области права более 10 лет",
    "certified_lawyer_licensed": "Аттестованный юрист, лицензия на оказание юридических услуг Министерства Юстиции Республики Беларусь",
    "experience_in_state_control_and_supervisory_bodies": "Опыт работы в государственных контрольных и надзорных органах, руководящие должности в компаниях, специализирующихся на оказании юридических услуг",
    "conducting_cases_in_court": "Ведение дел в суде",
    "working_with_bailiffs_experience": "Опыт работы с судебными исполнителями",
    "communication_with_contractors_and_correspondence_in_english": "Общение с контрагентами, ведение переписки на английском языке",
    "confidentiality": "Соблюдение конфиденциальности",

    "areas_of_our_professional_interest": "Сферы нашего профессионального интереса",
    "information_technology": "Информационные технологии",
    "retail_and_services": "Розничная торговля и услуги",
    "wholesale_and_b2b": "Оптовая торговля и B2B",
    "foreign_economic_activity": "Внешнеэкономическая деятельность",
    "investment_and_production": "Инвестиции и Производство",

    "types_of_services": "Виды оказываемых услуг",
    "full_legal_support_of_business": "Полное юридическое сопровождение бизнеса",
    "registration_and_reorganization_of_enterprises": "Регистрация и реорганизация компаний",
    "debt_collection": "Взыскание долгов",
    "representation_of_clients_in_state_bodies": "представительство интересов клиента в государственных органах",
    "work_with_foreign_companies_and_migrant_workers": "Работа с зарубежными компаниями и трудовыми мигрантами",
    "investment_documentation_development": "Разработка инвестиционной документации",

    "by_choosing_us,_you_get": "Выбирая нас, Вы получаете",
    "comprehensive_legal_services_by_a_team_of_professionals": "Комплексные юридические услуги от команды профессионалов",
    "flexible_terms_of_cooperation,_based_on_your_priorities": "Гибкие условия сотрудничества, исходя из Ваших приоритетов",
    "legal_protection_for_your_business": "Надежную правовую защиту Вашего бизнеса",

    //RATES
    "for_residents_of_the_republic_of_belarus": "для резидентов Республики Беларусь",

    "rates_for_legal_services_in_the_field_of_state_registration_(reorganization)_of_business_entities_(llc_(odl),_pue,_sp": "Тарифы на юридические услуги в области государственной регистрации (реорганизации) субъектов хозяйствования (ООО (ОДО), ЧУП, ИП",
    "preparation_of_documents_for_the_state_registration_of_the_company_(alc),_pue": "Подготовка пакета документов для государственной регистрации ООО (ОДО), ЧУП",
    "full_legal_support_of_state_registration_ltd_(odl),_pue": "Полное юридическое сопровождение по государственной регистрации ООО (ОДО), ЧУП",
    "full_legal_support_of_the_state_registration_of_ip": "Полное юридическое сопровождение при государственной регистрации ИП",
    "full_legal_support_of_the_procedure_of_legal_entity_reorganization": "Полное юридическое сопровождение процедуры реорганизации юридического лица",

    "rates_for_legal_services_in_the_field_of_representation": "Тарифы на юридические услуги в области представления",
    "full_legal_support_of_opening_the_representation_of_non-resident_organization": "Полное юридическое сопровождение открытия представительства организации нерезидента Республики Беларусь в Республике Беларусь",

    "rates_for_legal_services_when_making_changes_to_the_charter_of_the_business_entity": "Тарифы на юридические услуги при внесении изменений в устав коммерческой организации",
    "preparation_of_documents_for_making_changes_to_the_constituent_documents_of_a_legal_entity_in_connection_with_the_change_of_its_name": "Подготовка пакета документов для внесения изменений в учредительные документы юридического лица в связи с изменением его наименования, размера уставного фонда, состава участников, законодательства, в соответствии с которым требуется внесение изменений и (или) дополнений, другим фактическим обстоятельствам, содержащимся в уставе",

    "rates_for_other_legal_services_in_the_field_of_corporate_law": "Тарифы на иные юридические услуги в области корпоративного права",
    "preparation_of_draft_documents_for_convening_and_holding_the_general_meeting_of_the_business_association": "Подготовка проектов документов для созыва и проведения общего собрания участников хозяйственного общества",
    "preparation_of_draft_documents_for_the_transaction_for_the_disposal_of_shares_in_the_authorized_capital_of_llc_(odl)": "Подготовка проектов документов для совершения сделки по отчуждению доли в уставном фонде ООО (ОДО)",

    "rates_for_the_development_of_projects_of_different_types_of_contracts": "Тарифы на разработку проектов различных видов договоров",
    "economic_development_of_the_draft_treaty": "Разработка проекта хозяйственного договора",
    "drafting_foreign_economic_agreement": "Разработка проекта внешнеэкономического договора",
    "development_of_the_labor_contract_projects,_contracts,_contract": "Разработка проектов трудового договора, контрактов, договора подряда",

    "rates_for_legal_services_for_legal_entities_in_the_sphere_of_labor_migration": "Тарифы на юридические услуги для юридических лиц в сфере трудовой миграции",
    "preparation,_collection_of_documents,_support_for_obtaining_the_right_of_residence_in_the_republic_of_belarus": "Подготовка, сбор документов, сопровождение получения права на проживание в Республике Беларусь",
    "preparation,_collection_of_documents,_support_for_obtaining_a_residence_permit_in_the_republic_of_belarus": "Подготовка, сбор документов, сопровождение получения вида на жительство в Республике Беларусь",
    "preparation_of_documents_for_obtaining_a_special_right_to_engage_in_work_in_the_republic_of_belarus": "Подготовка пакета документов для получения специального права на занятие трудовой деятельностью в Республике Беларусь",
    "full_legal_support_for_obtaining_a_special_right_to_engage_in_work_in_the_republic_of_belarus": "Полное юридическое сопровождение получения специального права на занятие трудовой деятельностью в Республике Беларусь",

    "rates_for_the_preparation_of_legal_documents_for_courts,_enforcement_authorities,_notaries": "Тарифы по подготовке процессуальных документов для судов, органов принудительного исполнения, нотариата",
    "study_materials_and_giving_advice_on_possible_options_for_the_protection_of_rights_and_legal_interests_of_the_client": "Изучение материалов и дача консультаций о возможных вариантах защиты прав и законных интересов клиента",
    "consultation_on_the_possibility_of_filing_a_claim_to_the_economic_court,_the_formation_of_a_position_on_the_case": "Консультации по вопросам о возможности подачи искового заявления в хозяйственный суд, формирование позиции по делу",
    "preparation_of_claims_(proposal_for_voluntary_settlement_of_the_dispute),_the_response_to_the_claim": "Подготовка претензии (предложения о добровольном урегулировании спора), ответа на претензию",
    "preparing_the_statement_of_claim,_recall_the_statement_of_claim": "Подготовка искового заявления, отзыва на исковое заявление",
    "preparation_of_the_application_for_commencement_of_writ_proceedings,_comment_on_the_statement_of_writ_proceedings": "Подготовка заявления о возбуждении приказного производства, отзыва на заявление о возбуждении приказного производства",
    "preparation_of_appeal,_cassation_complaints,_complaints_of_supervision,_revocation_on_appeal,_appeal,_on_newly_discovered_facts": "Подготовка апелляционной, кассационной жалобы, жалобы в порядке надзора, отзыва на апелляционную, кассационную жалобу, по вновь открывшимся обстоятельствам",
    "preparation_of_the_extradition_documents_of_executive_inscriptions": "Подготовка пакета документов о выдаче исполнительной надписи",
    "preparing_the_application_for_commencement_of_enforcement_proceedings": "Подготовка заявления о возбуждении исполнительного производства",
    "preparation_of_other_procedural_documents": "Подготовка прочих процессуальных документов",
    "representation_in_enforcement_proceedings": "Представление интересов в исполнительном производстве",

    "rates_for_legal_advice_and_legal_assistance_for_any_other_legal_matters": "Тарифы на юридические консультации и правовую помощь по иным правовым вопросам",
    "verbal_legal_advice": "Устные юридические консультации",
    "written_legal_advice": "Письменные юридические консультации",
    "representing_clients_before_government_agencies,_contractors_and_other_third_parties_in_the_course_of_his_instructions": "Представление интересов клиента перед государственными органами, контрагентами и иными третьими лицами в ходе исполнения его поручения",
    "selection_of_materials,_legislation_on_specific_customer_category": "Подбор материалов, законодательных актов по определённой клиентом тематике",

    "or_%_of_foreclosure": "либо % от взыскания",
    "per_hour": "за час",
    //Rates END

    "our_services_-_a_guarantee_of_the_right_steps_in_the_business": "Наши услуги – гарантия правильных шагов в бизнесе",

    "services_provided_include": "Предоставляемые услуги",
    "registration_and_reorganization_of_legal_entities": "Регистрация и реорганизация юридических лиц",
    "detailed_study_of_constituent_documents": "Детальная проработка учредительных документов",
    "bringing_the_constituent_documents_in_compliance_with_the_law": "Приведение учредительных документов с соответствие с законодательством",
    "registration_and_reorganization_of_legal_entities_branches_and_representative_offices": "Регистрация и реорганизация юридических лиц филиалов и представительств",
    "registration_of_branches_and_representative_offices": "Регистрация филиалов и представительств",
    "amendments_and_preparation_of_the_new_edition_of_the_charter": "Внесение изменений и подготовка новых редакций уставов",
    "support_for_the_purchase_and_sale_transactions_of_shares_in_the_authorized_capital": "Сопровождение сделок по купле-продаже долей в уставном фонде, смены учредителей и регистрации этих изменений в государственных органах",
    "change_of_name_of_a_legal_entity": "Смена наименования юридического лица",
    "document_preparation": "Подготовка документов, сопровождение регистрации в качестве индивидуального предпринимателя",
    "support_economic_activity": "Сопровождение хозяйственной деятельности",
    "work_with_personnel": "Кадровая работа",
    "advice_on_legal_aspects_of_doing_business": "Консультирование о правовых аспектах ведения бизнеса",
    "drafting_and_legal_examination_of_economic_contracts": "Составление и правовая экспертиза хозяйственных договоров (договоры: поставки, подряда, возмездного оказания услуг, перевода долга, уступки права требования, франчайзинга и т.д.)",
    "obtaining_a_special_permit_for_labor_activity_in_the_republic_of_belarus_for_foreign_citizens": "Получение специального разрешения на право занятия трудовой деятельностью в Республике Беларусь для иностранных граждан, сопровождения получения права на временное проживание и вида на жительство для работников организаций",
    "obtaining_licenses_and_special_permits": "Получение лицензий и специальных разрешений, внесение изменений и дополнений в лицензии, продление срока действия лицензий",
    "obtaining_patents": "Получение патентов, регистрация объектов интеллектуальной собственности и знаков обслуживания, составление и правовая экспертиза лицензионных договоров, договоров франчайзинга",
    "copyright_protection": "Защита авторского права",
    "with_claims_related_work": "Претензионно - исковая работа, сопровождение взыскания",
    "negotiation_and_settlement_of_disputes_out_of_court": "Ведение переговоров, урегулирование споров в досудебном порядке",
    "preparation_of_claim_letters": "Составление претензионных писем, исковых заявлений, заявлений  в порядке приказного производства, возражений по делу, кассационных, апелляционных и надзорных жалоб",
    "preparation_of_applications_to_commit_the_executive_inscriptions": "Составление заявлений о совершении исполнительной надписи, подготовка соответствующего пакета документов",
    "support_of_debt_collection": "Сопровождение взыскания долгов (подготовка заявлений и сопровождение принудительного взыскания дебиторской задолженности, контроль в органах по принудительному исполнению (судебные исполнители), отыскание имущества должника, переговоры с должниками)",
    "work_in_the_field_of_administrative_law": "Работа в сфере административного права",
    "support_and_legal_protection_in_cases_of_administrative_offenses": "Сопровождение и правовая защита по делам об административных правонарушениях (изучение материалов дела, выработка стратегии защиты, обжалование постановлений)",
    "counseling": "Консультирование ",
    "consultancy_in_the_field_of_law": "Консультирование в сфере права: устные, письменные консультации",
    "preparation_of_official_requests": "Составление официальных обращений, деловых писем"
};