module.exports = {
    "about": "О нас",
    "contact": "Контакты",
    "home": "Главная",
    "services": "Услуги",
    "address_text": "220002 Минск, ул. Киселева, 55, офис 22",
    "email": "Почта",
    "name": "Имя",
    "submit": "Отправить",
    "copyright": "© 2016 Aenean porta condimentum, ВСЕ ПРАВА ЗАЩИЩЕНЫ.",
    "message": "Сообщение",

    "experience": "Опыт",
    "blah_blah_blah": "бла бла бла",
    "why_choose_us": "Почему стоит выбрать нас",
    "legal_and_advisory_services": "Юридические и консультативные (консалтинговые) услуги, правовое сопровождение бизнеса",
    "our_company_specializes_in_legal_consulting_business": "Наша компания специализируется на юридическом консалтинге бизнеса. Системная правовая поддержка наш",
    "the_accumulated_experience_allows_us" : "Наработанный опыт позволяет нам профессионально и эффективно организовать и обслуживать Ваш бизнес. поддержка действующего бизнеса, в рамках которой юристы оказывают различный спектр услуг, позволяющих работать без опасений.",
    "our_customers": "Наши клиенты",
    "80_percent_of_our_customers_are_companies_from_the_it_sphere": "80% наших клиентов являются компании из IT сферы",
    "work_experience_in_the_field_of_law_for_over_10_years": "Стаж работы в области права более 10 лет",
    "certified_lawyer_licensed": "Аттестованный юрист, лицензия на оказание юридических услуг Министерства Юстиции Республики Беларусь",
    "experience_in_state_control_and_supervisory_bodies": "Опыт работы в государственных контрольных и надзорных органах, руководящие должности в компаниях, специализирующихся на оказании юридических услуг",
    "conducting_cases_in_court": "Ведение дел в суде",
    "working_with_bailiffs_experience": "Опыт работы с судебными исполнителями",
    "communication_with_contractors_and_correspondence_in_english": "Общение с контрагентами, ведение переписки на английском языке",
    "confidentiality": "Соблюдение конфиденциальности",

    "services_provided_include": "Предоставляемые услуги включают",
    "registration_and_reorganization_of_legal_entities": "Регистрация и реорганизация юридических лиц",
    "detailed_study_of_constituent_documents": "Детальная проработка учредительных документов",
    "bringing_the_constituent_documents_in_compliance_with_the_law": "Приведение учредительных документов с соответствие с законодательством",
    "registration_and_reorganization_of_legal_entities_branches_and_representative_offices": "Регистрация и реорганизация юридических лиц филиалов и представительств",
    "registration_of_branches_and_representative_offices": "Регистрация филиалов и представительств",
    "amendments_and_preparation_of_the_new_edition_of_the_charter": "Внесение изменений и подготовка новых редакций уставов",
    "support_for_the_purchase_and_sale_transactions_of_shares_in_the_authorized_capital": "Сопровождение сделок по купле-продаже долей в уставном фонде, смены учредителей и регистрации этих изменений в государственных органах",
    "change_of_name_of_a_legal_entity": "Смена наименования юридического лица",
    "document_preparation": "Подготовка документов, сопровождение регистрации в качестве индивидуального предпринимателя",
    "support_economic_activity": "Сопровождение хозяйственной деятельности",
    "work_with_personnel": "Кадровая работа",
    "advice_on_legal_aspects_of_doing_business": "Консультирование о правовых аспектах ведения бизнеса",
    "drafting_and_legal_examination_of_economic_contracts": "Составление и правовая экспертиза хозяйственных договоров (договоры: поставки, подряда, возмездного оказания услуг, перевода долга, уступки права требования, франчайзинга и т.д.)",
    "obtaining_a_special_permit_for_labor_activity_in_the_republic_of_belarus_for_foreign_citizens": "Получение специального разрешения на право занятия трудовой деятельностью в Республике Беларусь для иностранных граждан, сопровождения получения права на временное проживание и вида на жительство для работников организаций",
    "obtaining_licenses_and_special_permits": "Получение лицензий и специальных разрешений, внесение изменений и дополнений в лицензии, продление срока действия лицензий",
    "obtaining_patents": "Получение патентов, регистрация объектов интеллектуальной собственности и знаков обслуживания, составление и правовая экспертиза лицензионных договоров, договоров франчайзинга",
    "copyright_protection": "Защита авторского права",
    "with_claims_related_work": "Претензионно - исковая работа, сопровождение взыскания",
    "negotiation_and_settlement_of_disputes_out_of_court": "Ведение переговоров, урегулирование споров в досудебном порядке",
    "preparation_of_claim_letters": "Составление претензионных писем, исковых заявлений, заявлений  в порядке приказного производства, возражений по делу, кассационных, апелляционных и надзорных жалоб",
    "preparation_of_applications_to_commit_the_executive_inscriptions": "Составление заявлений о совершении исполнительной надписи, подготовка соответствующего пакета документов",
    "support_of_debt_collection": "Сопровождение взыскания долгов (подготовка заявлений и сопровождение принудительного взыскания дебиторской задолженности, контроль в органах по принудительному исполнению (судебные исполнители), отыскание имущества должника, переговоры с должниками)",
    "work_in_the_field_of_administrative_law": "Работа в сфере административного права",
    "support_and_legal_protection_in_cases_of_administrative_offenses": "Сопровождение и правовая защита по делам об административных правонарушениях (изучение материалов дела, выработка стратегии защиты, обжалование постановлений)",
    "counseling": "Консультирование ",
    "consultancy_in_the_field_of_law": "Консультирование в сфере права: устные, письменные консультации",
    "preparation_of_official_requests": "Составление официальных обращений, деловых писем"
};